import pywhatkit
import pyautogui
import webbrowser as wb
import time
# pywhatkit.sendwhatmsg_instantly("+917350513246","msg",1)
wb.open("web.whatsapp.com")
time.sleep((20))
for _ in range(100):
    pyautogui.press(("H"))
    pyautogui.press(("a"))
    pyautogui.press(("a"))
    pyautogui.press(("P"))
    pyautogui.press(("p"))
    pyautogui.press(("y"))
    pyautogui.press(("enter"))
    pyautogui.press(("B"))
    pyautogui.press(("i"))
    pyautogui.press(("r"))
    pyautogui.press(("t"))
    pyautogui.press(("h"))
    pyautogui.press(("d"))
    pyautogui.press(("a"))
    pyautogui.press(("y"))
    pyautogui.press(("enter"))
    pyautogui.press(("D"))
    pyautogui.press(("a"))
    pyautogui.press(("r"))
    pyautogui.press(("l"))
    pyautogui.press(("i"))
    pyautogui.press(("g"))
    pyautogui.press(("enter"))
    pyautogui.press(("D"))
    pyautogui.press(("i"))
    pyautogui.press(("d"))
    pyautogui.press(("i"))
    pyautogui.press(("enter"))

